pub const ORGANIZER:        &'static str = "Organizer";
pub const JAMMER:           &'static str = "Jammer";
pub const PROGRAMMER:       &'static str = "Programmer";
pub const ARTIST_2D:        &'static str = "2D Artist";
pub const ARTIST_3D:        &'static str = "3D Artist";
pub const SOUND_DESIGNER:   &'static str = "Sound Designer";
pub const MUSICIAN:         &'static str = "Musician";
pub const IDEA_GUY:         &'static str = "Idea Guy";
pub const BOARD_GAMES:      &'static str = "Board Games";
